# Generated by Django 2.0 on 2020-02-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_is_headman'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
