# Generated by Django 2.0 on 2020-02-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200213_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='groupnumber',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.BooleanField(default=False),
        ),
    ]
