# Generated by Django 2.0 on 2020-03-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_user_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('is_headman', models.BooleanField(default=False)),
            ],
        ),
    ]
