# Generated by Django 2.0 on 2020-03-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_headman'),
    ]

    operations = [
        migrations.AddField(
            model_name='headman',
            name='group',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
