# Generated by Django 2.0 on 2020-02-19 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mark', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marktxt',
            name='c_time',
        ),
    ]
